import type { IAlert, IDailyReport, IDeployment, INotifier, IPipelineStatus } from '@aker/ai-monitor-core';

/**
 * Email notifier configuration
 */
export interface IEmailConfig {
  host: string;
  port: number;
  secure?: boolean;
  auth: {
    user: string;
    pass: string;
  };
  from: string;
  to: string | string[];
}

/**
 * Email notifier implementation
 * Sends notifications via SMTP
 */
export class EmailNotifier implements INotifier {
  private config: IEmailConfig;
  private transporter: any;
  private enabled: boolean = false;

  constructor(config: IEmailConfig) {
    this.config = config;

    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const nodemailer = require('nodemailer');
      this.transporter = nodemailer.createTransport({
        host: config.host,
        port: config.port,
        secure: config.secure ?? false,
        auth: config.auth,
      });
      this.enabled = true;
    } catch (error) {
      console.error('Failed to initialize Email notifier. Make sure "nodemailer" package is installed.');
      console.error('Install with: npm install nodemailer');
      this.enabled = false;
    }
  }

  async send(message: string): Promise<void> {
    if (!this.enabled) {
      console.warn('Email notifier disabled - skipping notification');
      return;
    }

    try {
      await this.transporter.sendMail({
        from: this.config.from,
        to: this.config.to,
        subject: 'AI Monitor Notification',
        text: message,
        html: `<pre>${message}</pre>`,
      });
    } catch (error) {
      console.error('Failed to send Email notification:', error);
      throw error;
    }
  }

  async sendAlert(alert: IAlert): Promise<void> {
    if (!this.enabled) return;

    const timestamp = alert.timestamp || new Date();
    const subject = `[${alert.severity}] ${alert.title}`;

    const html = this.generateAlertHtml(alert, timestamp);
    const text = this.generateAlertText(alert, timestamp);

    await this.transporter.sendMail({
      from: this.config.from,
      to: this.config.to,
      subject: subject,
      text: text,
      html: html,
    });
  }

  async sendPipelineStatus(status: IPipelineStatus): Promise<void> {
    if (!this.enabled) return;

    const subject = `Pipeline ${status.status}: ${status.jobName} #${status.buildNumber}`;
    const html = this.generatePipelineHtml(status);
    const text = this.generatePipelineText(status);

    await this.transporter.sendMail({
      from: this.config.from,
      to: this.config.to,
      subject: subject,
      text: text,
      html: html,
    });
  }

  async sendDeploymentNotification(deployment: IDeployment): Promise<void> {
    if (!this.enabled) return;

    const subject = `Deployment ${deployment.status}: ${deployment.environment} v${deployment.version}`;
    const html = this.generateDeploymentHtml(deployment);
    const text = this.generateDeploymentText(deployment);

    await this.transporter.sendMail({
      from: this.config.from,
      to: this.config.to,
      subject: subject,
      text: text,
      html: html,
    });
  }

  async sendDailyReport(report: IDailyReport): Promise<void> {
    if (!this.enabled) return;

    const subject = `Daily Health Report - ${report.date.toLocaleDateString()}`;
    const html = this.generateReportHtml(report);
    const text = this.generateReportText(report);

    await this.transporter.sendMail({
      from: this.config.from,
      to: this.config.to,
      subject: subject,
      text: text,
      html: html,
    });
  }

  private generateAlertHtml(alert: IAlert, timestamp: Date): string {
    const severityColor = this.getSeverityColor(alert.severity);
    const metricsHtml = alert.metrics ? `<h3>Metrics</h3><pre>${JSON.stringify(alert.metrics, null, 2)}</pre>` : '';

    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <div style="background: ${severityColor}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0;">${alert.severity}: ${alert.title}</h1>
        </div>
        <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 5px 5px;">
          <p>${alert.message}</p>
          <p><strong>Time:</strong> ${timestamp.toISOString()}</p>
          ${metricsHtml}
        </div>
        <div style="margin-top: 20px; color: #888; font-size: 12px;">
          Generated by AI Monitor
        </div>
      </div>
    `;
  }

  private generateAlertText(alert: IAlert, timestamp: Date): string {
    const metricsStr = alert.metrics ? `\n\nMetrics:\n${JSON.stringify(alert.metrics, null, 2)}` : '';

    return `
${alert.severity}: ${alert.title}

${alert.message}

Time: ${timestamp.toISOString()}${metricsStr}

---
Generated by AI Monitor
    `.trim();
  }

  private generatePipelineHtml(status: IPipelineStatus): string {
    const statusColor = this.getStatusColor(status.status);
    const changesHtml =
      status.changes && status.changes.length > 0
        ? `<h3>Changes</h3><ul>${status.changes.map((c) => `<li>${c}</li>`).join('')}</ul>`
        : '';

    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <div style="background: ${statusColor}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0;">${status.jobName} - Build #${status.buildNumber}</h1>
        </div>
        <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 5px 5px;">
          <p><strong>Status:</strong> ${status.status}</p>
          ${status.duration ? `<p><strong>Duration:</strong> ${this.formatDuration(status.duration)}</p>` : ''}
          ${status.url ? `<p><a href="${status.url}">View Build</a></p>` : ''}
          ${changesHtml}
        </div>
      </div>
    `;
  }

  private generatePipelineText(status: IPipelineStatus): string {
    const changesStr =
      status.changes && status.changes.length > 0
        ? `\n\nChanges:\n${status.changes.map((c) => `• ${c}`).join('\n')}`
        : '';

    return `
${status.jobName} - Build #${status.buildNumber}

Status: ${status.status}
${status.duration ? `Duration: ${this.formatDuration(status.duration)}` : ''}
${status.url ? `URL: ${status.url}` : ''}${changesStr}
    `.trim();
  }

  private generateDeploymentHtml(deployment: IDeployment): string {
    const statusColor = deployment.status === 'SUCCESS' ? '#28a745' : '#dc3545';

    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <div style="background: ${statusColor}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0;">Deployment - ${deployment.environment}</h1>
        </div>
        <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 5px 5px;">
          <p><strong>Version:</strong> ${deployment.version}</p>
          <p><strong>Status:</strong> ${deployment.status}</p>
          ${deployment.duration ? `<p><strong>Duration:</strong> ${this.formatDuration(deployment.duration)}</p>` : ''}
          ${deployment.url ? `<p><a href="${deployment.url}">View Environment</a></p>` : ''}
        </div>
      </div>
    `;
  }

  private generateDeploymentText(deployment: IDeployment): string {
    return `
Deployment - ${deployment.environment}

Version: ${deployment.version}
Status: ${deployment.status}
${deployment.duration ? `Duration: ${this.formatDuration(deployment.duration)}` : ''}
${deployment.url ? `URL: ${deployment.url}` : ''}
    `.trim();
  }

  private generateReportHtml(report: IDailyReport): string {
    const overallStatus = report.totalAlerts === 0 ? '✅ Healthy' : '⚠️ Issues Found';
    const topIssuesHtml =
      report.topIssues.length > 0
        ? `<h3>Top Issues</h3><ol>${report.topIssues.map((issue) => `<li>${issue}</li>`).join('')}</ol>`
        : '';

    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <div style="background: #007bff; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
          <h1 style="margin: 0;">📊 Daily Health Report</h1>
          <p style="margin: 5px 0 0 0;">${report.date.toLocaleDateString()}</p>
        </div>
        <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 5px 5px;">
          <h2>Overall Status: ${overallStatus}</h2>
          <ul>
            <li><strong>Total Alerts:</strong> ${report.totalAlerts}</li>
            <li><strong>Critical:</strong> ${report.criticalAlerts}</li>
            <li><strong>Auto-Fixed:</strong> ${report.autoFixes}</li>
            <li><strong>Uptime:</strong> ${report.uptime}</li>
          </ul>
          ${topIssuesHtml}
        </div>
      </div>
    `;
  }

  private generateReportText(report: IDailyReport): string {
    const overallStatus = report.totalAlerts === 0 ? '✅ Healthy' : '⚠️ Issues Found';
    const topIssuesStr =
      report.topIssues.length > 0
        ? `\n\nTop Issues:\n${report.topIssues.map((issue, i) => `${i + 1}. ${issue}`).join('\n')}`
        : '';

    return `
📊 Daily Health Report - ${report.date.toLocaleDateString()}

Overall Status: ${overallStatus}

Summary:
• Total Alerts: ${report.totalAlerts}
• Critical: ${report.criticalAlerts}
• Auto-Fixed: ${report.autoFixes}
• Uptime: ${report.uptime}${topIssuesStr}
    `.trim();
  }

  private getSeverityColor(severity: string): string {
    switch (severity) {
      case 'CRITICAL':
        return '#dc3545';
      case 'WARNING':
        return '#ffc107';
      case 'INFO':
        return '#17a2b8';
      default:
        return '#6c757d';
    }
  }

  private getStatusColor(status: string): string {
    switch (status) {
      case 'SUCCESS':
        return '#28a745';
      case 'FAILURE':
        return '#dc3545';
      case 'ABORTED':
        return '#6c757d';
      case 'UNSTABLE':
        return '#ffc107';
      default:
        return '#6c757d';
    }
  }

  private formatDuration(seconds: number): string {
    if (seconds < 60) return `${seconds}s`;
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ${seconds % 60}s`;
    return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`;
  }
}
